import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
    site: "@chinari819",
    title: "ポポニウム",
    description: "ポポニウム",
    images: "https://github.com/chinari819/poponium/blob/main/public/img/ieiri.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
